import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';
import { AuthProvider } from '@/components/auth/AuthProvider';
import { AuthSessionProvider } from '@/components/auth/SessionProvider';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { Navbar } from '@/components/nav/Navbar';
import { Footer } from '@/components/nav/Footer';
import { LoginModal } from '@/components/auth/LoginModal';
import { Toaster } from 'sonner';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://topbun.vercel.app'),
  title: {
    default: 'TopBun - 대한민국 No.1 버거 커뮤니티',
    template: '%s | TopBun',
  },
  description: '리뷰, 랭킹, 버거 월드컵까지 — 버거의 모든 것',
  keywords: ['버거', '햄버거', '리뷰', '랭킹', '월드컵', '커뮤니티', 'burger', 'review'],
  authors: [{ name: 'TopBun Team' }],
  creator: 'TopBun',
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'TopBun',
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: '/icon-192x192.png',
    apple: '/icon-192x192.png',
  },
  openGraph: {
    type: 'website',
    locale: 'ko_KR',
    alternateLocale: 'en_US',
    url: 'https://topbun.vercel.app',
    siteName: 'TopBun',
    title: 'TopBun - 대한민국 No.1 버거 커뮤니티',
    description: '리뷰, 랭킹, 버거 월드컵까지 — 버거의 모든 것',
    // Images auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'TopBun - 대한민국 No.1 버거 커뮤니티',
    description: '리뷰, 랭킹, 버거 월드컵까지 — 버거의 모든 것',
    // Images auto-generated by twitter-image.tsx
  },
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: '#E76F51',
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[var(--color-bg)] text-[var(--color-text)] min-h-screen flex flex-col`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider>
            <AuthSessionProvider>
              <AuthProvider>
                <Navbar />
                <LoginModal />
                <Toaster position="bottom-center" richColors />
                <main className="flex-1">
                  {children}
                </main>
                <Footer />
              </AuthProvider>
            </AuthSessionProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
